### ISSUE TITLE
NUXT error 500

### ISSUE THREAD

**Issue by chefjuanpi** [CocoaWebStudio/nuxtify-app#4]
exports is not defined in ES module scope

500
exports is not defined in ES module scope
at $id_60f0615f (file:///C:/git/shopify/nuxtify-app/.nuxt/dist/server/server.mjs:88:23)
at __instantiateModule__ (file:///C:/git/shopify/nuxtify-app/.nuxt/dist/server/server.mjs:7406:9)
at __ssrLoadModule__ (file:///C:/git/shopify/nuxtify-app/.nuxt/dist/server/server.mjs:7353:25)
at ssrImport (file:///C:/git/shopify/nuxtify-app/.nuxt/dist/server/server.mjs:7378:13)
at $id_5d08de08 (file:///C:/git/shopify/nuxtify-app/.nuxt/dist/server/server.mjs:15:37)
at __instantiateModule__ (file:///C:/git/shopify/nuxtify-app/.nuxt/dist/server/server.mjs:7406:9)
at __ssrLoadModule__ (file:///C:/git/shopify/nuxtify-app/.nuxt/dist/server/server.mjs:7353:25)
at file:///C:/git/shopify/nuxtify-app/.nuxt/dist/server/server.mjs:7419:22
at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
at async Promise.all (index 0)

**Comment by chefjuanpi** [comment]
Not possible for not to use Nuxt 3 on windows directly, you should use WSL
